config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  get 'users/edit'
  get 'tasks/index'
  get 'tasks/show'
  get 'tasks/new'
  get 'tasks/edit'
  devise_for :users

  get 'user/:id/show' => "users#show" , as: 'user_show'
  get 'user/:id/edit' => "users#edit" , as: 'user_edit'
  post 'user/:id/update' => "users#update" , as: 'user_update'

  get 'building/:id/show' => "buildings#show"
  post 'building/:location_id/:building_id' => "buildings#enter" , as: 'location_id'
  # get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/' => "home#index", as: 'home_index'


  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  authenticated :users do
      root :to => "home#index"
  end

  unauthenticated :users do
      root :to => "home#index"
 end


  # resources :users, only: [:show]
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/building.rb
class Building < ApplicationRecord
    has_many :locations

    def locations
        return Location.where(building_id: self.id)
    end
end

app/models/location.rb
class Location < ApplicationRecord
    belongs_to :building
    has_many :users

    def building
        return Location.find_by(id: self.building_id)
    end
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks, dependent: :destroy
  belongs_to :location, optional: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
      def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :username])
      end

    def after_sign_in_path_for(resource_or_scope)
      home_index_path
    end

    def after_sign_out_path_for(resource_or_scope)
      home_index_path
    end
end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController
  before_action :authenticate_user!
  def show
    @building = Building.find_by(id: params[:id])
    @locations = @building.locations
    @users = User.all
  end

  def enter
    @user = current_user
    @user.location_id = params[:location_id]
    @user.save
    redirect_to controller: 'buildings', action: 'show', id: params[:building_id]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
    @current_user = current_user
    if @current_user.location_id == nil
      @current_user.location_id = 1
      @current_user.save
    end
    @users = User.all
    for @user in @users do
      @user.location = Location.find(@user.location_id)
    end
    @location = Location.find(current_user.location_id)
    @location_room = @location.room
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
# 認証済みであることを確認
  before_action :authenticate_user!

  def index
    @tasks = current_user.tasks
  end

  def show
    @task = target_task params[:id]
  end

  def new
    @task = Task.new
  end

  def create
    @task = current_user.tasks.new task_params
    @task.save!
    redirect_to @task
  end

  def edit
    @task = target_task params[:id]
  end

  def update
    @task = target_task params[:id]
    @task.update(task_params)
    redirect_to @task
  end

  def destroy
    @task = target_task params[:id]
    @task.destroy
    redirect_to tasks_url
  end

  private
  def target_task task_id
    current_user.tasks.where(id: task_id).take
  end

  def task_params
    params.require(:task).permit(:title, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.username = params[:username]
    @user.student_number = params[:student_number]
    @user.comment = params[:comment]

    if params[:image]
      image = params[:image]
      @extention = File.extname(image.original_filename)
      @user.icon_image_name = "#{@user.id}.#{@extention}"
      File.binwrite("public/user_images/#{@user.icon_image_name}",image.read)
    end

    @user.save
    redirect_to("/user/#{@user.id}/show")
  end

end

def image_type(file_path)
  File.open(file_path, 'rb') do |f|
    begin
      header = f.read(8)
      f.seek(-12, IO::SEEK_END)
      footer = f.read(12)
    rescue
      return nil
    end

    if header[0, 2].unpack('H*') == %w(ffd8) && footer[-2, 2].unpack('H*') == %w(ffd9)
      return 'jpg'
    elsif header[0, 3].unpack('A*') == %w(GIF) && footer[-1, 1].unpack('H*') == %w(3b)
      return 'gif'
    elsif header[0, 8].unpack('H*') == %w(89504e470d0a1a0a) && footer[-12,12].unpack('H*') == %w(0000000049454e44ae426082)
      return 'png'
    end
  end
  nil
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/buildings/show.html.erb
<div class="nav_bar">
    <span class="nav_link"><%= link_to(:controller => "home", :action => "index") do %><%= image_tag('back.png', :class => "back_img") %><% end %></span>
    <span class="menu_text"><%= @building.name %></span>
    <span></span>
</div>

<div class="contents">
        <% (1..@building.storey).each do |n| %>
            <div class="floor">
                <div class="floor_title"><%= n %>階</div> 
                <ul class="floor_list">
                <% @locations.each do |location| %>
                    <% if n == location.floor %>
                    <li class="room">
                    <div class="room_name"><%= location.room %><%= button_to 'enter',  location_id_path(location_id:location.id, building_id: @building.id) , :method => :post %></div>
                    
                    <% @users.each do |user| %>
                        <% if user.location_id == location.id %>
                            <div class="user">
                                <%= image_tag("/user_images/#{user.icon_image_name}", :class => "user_icon") %>
                                <span class="users"><%= user.username%></span>
                            </div> 
                        <% end %>
                    <% end %>
                    </li>
                    <% end %>
                <% end %>
                </ul>
            </div>
        <% end %>
    </div>
</div>

app/views/home/index.html.erb
<% if user_signed_in? %>
<div class="nav_bar">
    <div id="nav-drawer">
        <input id="nav-input" type="checkbox" class="nav-unshown">
        <label id="nav-open" for="nav-input"><span></span></label>
        <label class="nav-unshown" id="nav-close" for="nav-input"></label>
        <div id="nav-content">
            <div class="user_wrapper">
                <div class="icon_username">
                <%= image_tag("/user_images/#{current_user.icon_image_name}", :class => "user_icon") %>
                    <span class="username user_profile_data"><%= current_user.username %></span>
                </div>
                <div class="user_profiles">
                    <div class="user_profile">
                        <span class="user_profile_ttl">コメント</span>
                        <span class="comment user_profile_data"><%= current_user.comment %></span>
                    </div>
                    <div class="user_profile">
                        <span class="user_profile_ttl">学籍番号</span>
                        <span class="student_number user_profile_data"><%= current_user.student_number %></span>
                    </div>
                    <div class="user_profile">
                        <span class="user_profile_ttl">部屋</span>
                        <span class="location_room user_profile_data"><%= @location_room %></span>
                    </div>
                    <div class="edit_button"><%= link_to('edit',user_edit_path(id: current_user.id))%></div>
                </div>
            </div>
            <div class="logout_button"><%= link_to 'logout', destroy_user_session_path, method: :delete %></div>
            
        </div>
    </div>
    <span class="menu_text">HOME</span>
    <span class="to_arrange"></span>
</div>
<div class="contents">
    <div class="map_area">
        <%= image_tag('map2.png', :class => "map_img") %>
        <div class="building kobo"><%= link_to "工房棟", :controller => "buildings", :action => "show", :id => 2 %></div>
        <div class="building kenkyu"><%= link_to "研究棟", :controller => "buildings", :action => "show", :id => 3 %></div>
        <div class="building kanri"><%= link_to "管理棟", :controller => "buildings", :action => "show", :id => 4 %></div>
        <div class="building toshokan"><%= link_to "図書館棟", :controller => "buildings", :action => "show", :id => 5 %></div>
        <div class="building geijutukougaku"><%= link_to "芸術工学棟", :controller => "buildings", :action => "show", :id => 6 %></div>
        <div class="building shokudou"><%= link_to "食堂", :controller => "buildings", :action => "show", :id => 7 %></div>
        <div class="building sports"><%= link_to "スポーツコート", :controller => "buildings", :action => "show", :id => 8 %></div>

    </div>
    <div class="friends_area">
        <ul class="friends_ul">
            <% @users.each do |user| %>
                <%= link_to(user_show_path(id: user.id)) do %>
                    <li class="friends_li">
                        <span class="friend_li_icon_username">
                            <%= image_tag("/user_images/#{user.icon_image_name}", :class => "user_icon") %>
                            <span class="username"><%=user.username %></span>
                        </span>
                        <span class="location"><%=user.location.room %></span>

                    </li>
                <% end %>
            <% end %>
        </ul>
    </div>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- headの中に書く -->
  <link rel="manifest" href="/manifest.json" />
  <meta name="apple-mobile-web-app-capable" content="yes"></head>
  <link rel="apple-touch-icon" href="<%=image_path("taku2018_icon.png")%>" />
    <title>I Am Here</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  <link rel="manifest" href="/manifest.json" />
<meta name="apple-mobile-web-app-capable" content="yes"></head>

  <body>
    <nav>
    <!-- 
      <% if user_signed_in? %>
      <% else %>
        <%= link_to 'サインアップ', new_user_registration_path %>
        <%= link_to 'ログイン', new_user_session_path %>
      <% end %>
    --> 
    </nav>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Tasks#edit</h1>
<p>Find me in app/views/tasks/edit.html.erb</p>
<div style="width: 300px;">
  <%= form_for(@task) do |f| %>
    <div>
      <%= f.label :title %>
      <%= f.text_field :title, size: 50 %>
    </div>
    <div>
      <%= f.label :description %>
      <%= f.text_area :description %>
    </div>
    <%= f.submit 'Submit' %>
  <% end %>
</div>
<p><%= link_to '一覧に戻る', tasks_url %></p>

app/views/tasks/index.html.erb
<h1>Tasks#index</h1>
<p>Find me in app/views/tasks/index.html.erb</p>
<table>
  <tr>
    <th>Id</th><th>Title</th><th>Description</th><th></th><th></th><th></th>
  </tr>
  <% @tasks.each do |task| %>
  <tr>
    <td><%= task.id %></td>
    <td><%= task.title %></td>
    <td><%= task.description %></td>
    <td><%= link_to 'Show', task_path(task) %></td>
    <td><%= link_to 'Edit', edit_task_path(task) %></td>
    <td><%= link_to 'Delete', task_path(task), method: :delete %></td>
  </tr>
  <% end %>
</table>
<p><%= link_to 'ToDoの作成', new_task_path %></p>

app/views/tasks/new.html.erb
<h1>Tasks#new</h1>
<p>Find me in app/views/tasks/new.html.erb</p>
<div style="width: 300px;">
  <%= form_for(@task) do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title, size: 50 %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
    <%= f.submit 'Submit' %>
  <% end %>
</div>
<p><%= link_to '一覧に戻る', tasks_url %></p>

app/views/tasks/show.html.erb
<h1>Tasks#show</h1>
<p>Find me in app/views/tasks/show.html.erb</p>
<table>
  <tr>
    <th>Title</th>
    <td><%= @task.title %></td></tr>
  <tr>
    <th>Description</th>
    <td><%= @task.description %></td>
  </tr>
  <tr>
    <th>User.Email</th>
    <td><%= @task.user.email %></td>
  </tr>
</table>
<p><%= link_to '一覧に戻る', tasks_url %></p>

app/views/users/edit.html.erb
<div class="nav_bar">
    <span class="nav_link"><%= link_to(:controller => "home", :action => "index") do %><%= image_tag('back.png', :class => "back_img") %><% end %></span>
    
    <span class="menu_text">EDIT</span>
    <span></span>
</div>
<%= form_tag(user_update_path(@user.id), method: :post, multipart: true) do %>
    <div class="profile edit">
        <div class="user_edit_form">
            <div class="image_wrapper">
                <%= image_tag("/user_images/#{@user.icon_image_name}", :class => "user_icon", :id => "preview") %>
                <label class="image_label" accept="image/*" for="file_photo">
                    画像を選択
                    <input class="image" name="image" type="file" id="file_photo" style="display:none;">
                </label>
                
            </div>
            
            <div class="username_wrapper">
                <div >芸工ネーム</div>
                <input name="username" value=<%= @user.username %>>
            </div>
             <div class="student_number_wrapper">
                <div>学籍番号</div>
                <input name="student_number" value=<%= @user.student_number %>>
            </div>
             <div class="comment_wrapper">
                <div>コメント</div>
                <textarea class="comment" name="comment"><%= @user.comment %></textarea>
            </div>

            
        </div>
    </div>
    <input class="save_btn" type="submit" value="save">
<% end %>
<%= link_to(user_show_path(id: current_user.id)) do %>
        <div class="back_btn">cansel</div>
<% end %>

<script>
$('#file_photo').on('change', function (e) {
    var reader = new FileReader();
    reader.onload = function (e) {
        $("#preview").attr('src', e.target.result);
    }
    reader.readAsDataURL(e.target.files[0]);
});
</script>

app/views/users/show.html.erb
<div class="nav_bar">
    <span class="nav_link"><%= link_to(:controller => "home", :action => "index") do %><%= image_tag('back.png', :class => "back_img") %><% end %></span>
    <span class="menu_text">PROFILE</span>
    <span></span>
</div>

<div class="profile">
    <%= image_tag("/user_images/#{@user.icon_image_name}", :class => "user_icon") %>
    <div class="profile_name"><span class="profile_ttl">芸工ネーム</span><span class="profile_data"><%= @user.username %><span></div>
    <div class="profile_student_number"><span class="profile_ttl">学籍番号</span><span class="profile_data"><%= @user.student_number %><span></div> 
    <div class="profile_room"><span class="profile_ttl">部屋</span><span class="profile_data"><%= @user.location.room %><span></div>
    <div class="profile_comment"><span class="profile_ttl">コメント</span><span class="profile_data"><%= @user.comment %><span></div>
</div>

<% if current_user.id == @user.id %>
    <%= link_to(user_edit_path(id: current_user.id)) do %>
            <div class="edit_btn">edit</div>
    <% end %>
<% end %>